name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.13.16

    steps:
      - uses: actions/checkout@v3

      - uses: coursier/cache-action@v6

      - name: setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'sbt'

      - name: setup SBT
        uses: sbt/setup-sbt@v1

      - name: build ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} clean check

      - name: slack
        uses: homoluctus/slatify@master
        if: failure() && github.ref == 'refs/heads/master'
        with:
          type: ${{ job.status }}
          job_name: Build
          url: ${{ secrets.SLACK_WEBHOOK }}