name: Publish new Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: evolution-gaming/scala-github-actions/.github/workflows/release.yml@v4
    secrets: inherit
    with:
      verify_sbt_command: 'clean; check'
      publish_sbt_command: 'build'